export const client = {
  name: "Domi Brothers LTD",
  tagline: "Professional Landscaper in Crawley — Quality You Can Trust",
  description: "Professional landscaper services in Crawley and surrounding areas. Trusted local experts with 13 Google reviews.",
  category: "Landscaper",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Crawley",
  county: "",
  postcode: "",
  basedIn: "Crawley",
  founderName: "Alfred",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "4.9",
  reviewCount: "13",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "Marcelo Coimbra", rating: 5, text: "Very good service removing a plant that was damaging house structure. Recommended", date: "6 months ago", badge: "Local Guide" },
    { name: "BOO ALI", rating: 5, text: "Fantastic job and rapid finish and would highly recommend", date: "6 months ago" },
    { name: "Sarah Vince", rating: 5, text: "Alfred and his team, arrived on time, carried out the work to a very high standard, very pleasant and professional from start to finish. Would highly recommend.", date: "8 months ago" },
    { name: "Joanna Wasacz", rating: 5, text: "Alfred done the grate job, my garden after winter looked really bad, and this man had knowledge to make all right. I am so happy now when I see my beautiful garden.  He give me answers for all my questions and help with everything.  Really recommend.", date: "11 months ago" },
    { name: "TimaLovesTravels sanni", rating: 5, text: "I had a great experience. From our first chat with Alfred!, we set up a schedule that worked well for both of us. He did a fantastic job on the fence and really paid attention to detail. Alfred also gave helpful tips on how to take care of the fence so it lasts longer. He was on time and very flexible, making the whole process easy and pleasant. I highly recommend the team!", date: "11 months ago" },
    { name: "Bashkim Kombetar", rating: 5, text: "Great job done by Domi Brothers Ltd ! I would highly recommend them ! Thank you guys  🙏 …", date: "a year ago" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "Domi Brothers LTD | Professional Landscaper in Crawley",
    description: "Professional landscaper in Crawley. 4.9 stars on Google with 13 reviews. Quality workmanship guaranteed.",
  },
};
